spring.application.name=SpeakFlow AI
spring.datasource.url=jdbc:postgresql://localhost:5432/speakflow_ai
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (should be at least 32 characters in production)
speakflow.jwt.secret=sP3aKfLoWaI_R3aLlY_V3rY_S3cUrE_S3CrEt_KeY_T0_U53
speakflow.jwt.expiration=86400000




groq.api.key=${GROQ_API_KEY}